# Generated by Django 3.1.5 on 2021-01-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='game_title',
        ),
    ]
